name: Debounce Validation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  debounce-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install requirements
        run: pip install -r tools/debounce_validation/requirements.txt

      - name: Run test suite
        run: python3 -m unittest discover -s tools/debounce_validation
