name: Debounce Validation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  debounce-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install requirements
        run: pip install -r tools/debounce_validation/requirements.txt

      - name: Run test suite
        run: python3 -m unittest discover -s tools/debounce_validation
