name: Debounce Validation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  debounce-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install requirements
        run: pip install -r tools/debounce_validation/requirements.txt

      - name: Run test suite
        run: python3 -m unittest discover -s tools/debounce_validation
